[package]
name = "clap-sh"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.5.6", features = ["string", "cargo"] }
color-print = "0.3.6"
knus = "3.2.0"
miette = { version = "5.1.1", features = ["fancy"] }

[profile.release]
strip = true